using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HermesProxy.SourceGen;

/// <summary>
/// Emits a <c>ToStringFast()</c> extension for every enum marked
/// <c>[HermesProxy.World.Enums.ToStringFast]</c>: a switch from each member to its name as a
/// string literal, falling back to <c>Enum.ToString()</c> for anything that is not a declared
/// member (an undefined value, or a combination of [Flags]).
/// </summary>
/// <remarks>
/// <para>
/// Literals are interned, so a hit allocates nothing and needs no warm-up, where
/// <c>Enum.ToString()</c> rebuilds the enum's whole name table after every GC. When two members
/// share a value the first one declared wins.
/// </para>
/// <para>
/// Every explicit <c>value.ToString()</c> on a marked enum in the project is also intercepted and
/// sent to <c>ToStringFast()</c>, so existing call sites get it without being edited. The
/// intercepted call still boxes the value (24 B) as the original did; a hot path should call
/// <c>ToStringFast()</c> directly. Interception only reaches calls written in this project's
/// source: string interpolation and a logger rendering the enum call ToString from library code,
/// and still need the name passed in.
/// </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class EnumNameGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "HermesProxy.World.Enums.ToStringFastAttribute";
    private const string InterceptorsNamespace = "HermesProxy.Generated";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // The transform returns plain strings, so the incremental cache compares by value and an
        // edit elsewhere in the project does not re-emit these files.
        var sources = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeFullName,
            static (node, _) => true,
            static (ctx, _) => Emit((INamedTypeSymbol)ctx.TargetSymbol));

        context.RegisterSourceOutput(sources, static (ctx, s) => ctx.AddSource(s.HintName, s.Source));

        var calls = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax
                {
                    ArgumentList.Arguments.Count: 0,
                    Expression: MemberAccessExpressionSyntax { Name.Identifier.ValueText: "ToString" },
                },
                static (ctx, ct) => FindToStringCall(ctx, ct))
            .Where(static c => c is not null)
            .Select(static (c, _) => c!.Value)
            .Collect();

        context.RegisterSourceOutput(calls, static (ctx, c) =>
        {
            if (!c.IsEmpty)
                ctx.AddSource("EnumToStringInterceptors.g.cs", EmitInterceptors(c));
        });
    }

    private static InterceptedCall? FindToStringCall(GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;
        var receiver = ((MemberAccessExpressionSyntax)invocation.Expression).Expression;

        if (ctx.SemanticModel.GetSymbolInfo(invocation, ct).Symbol is not IMethodSymbol { Parameters.Length: 0 } method
            || method.ContainingType.SpecialType is not (SpecialType.System_Enum or SpecialType.System_Object))
            return null;

        if (ctx.SemanticModel.GetTypeInfo(receiver, ct).Type is not INamedTypeSymbol { TypeKind: TypeKind.Enum } type
            || !type.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == AttributeFullName))
            return null;

        var location = ctx.SemanticModel.GetInterceptableLocation(invocation, ct);
        if (location is null)
            return null;

        string ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString() + ".";
        return new InterceptedCall(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            "global::" + ns + type.Name + "Names",
            location.Version,
            location.Data,
            location.GetDisplayLocation());
    }

    private static string EmitInterceptors(ImmutableArray<InterceptedCall> calls)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace System.Runtime.CompilerServices");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        sb.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
        sb.AppendLine("    {");
        sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(InterceptorsNamespace);
        sb.AppendLine("{");
        sb.AppendLine("    file static class EnumToStringInterceptors");
        sb.AppendLine("    {");

        int n = 0;
        foreach (var group in calls.GroupBy(c => (c.EnumFullName, c.NamesClass)).OrderBy(g => g.Key.EnumFullName, System.StringComparer.Ordinal))
        {
            if (n++ > 0)
                sb.AppendLine();
            foreach (var call in group.OrderBy(c => c.DisplayLocation, System.StringComparer.Ordinal))
            {
                sb.Append("        // ").AppendLine(call.DisplayLocation);
                sb.Append("        [global::System.Runtime.CompilerServices.InterceptsLocation(")
                  .Append(call.Version).Append(", \"").Append(call.Data).AppendLine("\")]");
            }
            // Enum.ToString() is declared on System.Enum and the compiler insists on that exact
            // receiver type (CS9148), so the call site still boxes, as the original call did. It
            // no longer rebuilds the name table; calling ToStringFast() directly avoids the box.
            sb.AppendLine("        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.Append("        public static string ToString").Append(n).AppendLine("(this global::System.Enum value)");
            sb.Append("            => ").Append(group.Key.NamesClass).Append(".ToStringFast((").Append(group.Key.EnumFullName).AppendLine(")value);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private readonly record struct InterceptedCall(string EnumFullName, string NamesClass, int Version, string Data, string DisplayLocation);

    private static (string HintName, string Source) Emit(INamedTypeSymbol type)
    {
        string enumName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string ns = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString();
        string className = type.Name + "Names";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (ns.Length > 0)
            sb.Append("namespace ").Append(ns).AppendLine(";");
        sb.AppendLine();
        sb.Append("internal static partial class ").AppendLine(className);
        sb.AppendLine("{");
        sb.Append("    public static string ToStringFast(this ").Append(enumName).AppendLine(" value) => value switch");
        sb.AppendLine("    {");

        var seen = new HashSet<object>();
        foreach (var field in type.GetMembers().OfType<IFieldSymbol>())
        {
            if (!field.IsConst || field.ConstantValue is null || !seen.Add(field.ConstantValue))
                continue;
            sb.Append("        ").Append(enumName).Append('.').Append(field.Name)
              .Append(" => \"").Append(field.Name).AppendLine("\",");
        }

        sb.AppendLine("        _ => value.ToString(),");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        string hint = (ns.Length > 0 ? ns + "." : "") + className + ".g.cs";
        return (hint, sb.ToString());
    }
}
